version: '3.3'

services:
  geekhunter:
    build: ./geekhunter
    # command: python manage.py runserver 0.0.0.0:8000  # use if we run internal django srv
    command: sh -c "python manage.py migrate && python manage.py loaddata fixtures/db.json && python manage.py collectstatic --noinput && gunicorn geekhunter.wsgi:application --bind 0.0.0.0:8000"

    # command: gunicorn geekhunter.wsgi:application --bind 0.0.0.0:8000
    # volumes:  # in production we comment this section because we do not change the files itself
    #   - ./geekhunter/:/home/geekhunter/  
    volumes:
      - pgstatic:/home/geekhunter/web/static/
      - pgmedia:/home/geekhunter/web/media/:rw

    # ports:  # if we use dev environment without nginx
    #   - 8000:8000
    expose: # if we use with nginx
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - pgstatic:/home/geekhunter/web/static/
      - pgmedia:/home/geekhunter/web/media/:rw
    ports:
      - 5050:80
    depends_on:
      - geekhunter

volumes:
  pgstatic:
  pgmedia: