# Generated by Django 4.0.2 on 2022-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
    ]
