# Generated by Django 4.0.2 on 2022-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_portaluser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_photo/'),
        ),
    ]
