# Generated by Django 4.0.1 on 2022-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topik',
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.CharField(blank=True, max_length=100, verbose_name='topic'),
        ),
    ]
