# Generated by Django 4.0.1 on 2022-01-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_resumes', to='employee_app.resume'),
        ),
    ]
