# Generated by Django 4.0.1 on 2022-01-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_alter_hrmanager_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanager',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_app.company'),
        ),
    ]
