# Generated by Django 4.0.2 on 2022-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_alter_card_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logo/'),
        ),
    ]
