# Generated by Django 4.0.1 on 2022-02-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_remove_card_id_alter_card_company'),
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritevacancies',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies_fav', to='company_app.company'),
            preserve_default=False,
        ),
    ]
