# Generated by Django 4.0.1 on 2022-01-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_favoriteresume_resume'),
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[('SENT', 'sent'), ('ACCEPTED', 'accepted'), ('NOT_ACCEPTED', 'not_accepted')], default='SENT', max_length=20, verbose_name='status')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('feedback', models.CharField(blank=True, max_length=500, verbose_name='feedback')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='employee_app.resume')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='company_app.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee_app.employee')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company_app.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('period', models.CharField(max_length=200, verbose_name='period')),
                ('position', models.CharField(max_length=300, verbose_name='position')),
                ('duties', models.CharField(blank=True, max_length=1000, verbose_name='duties')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_resumes', to='employee_app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=400, verbose_name='educational_institution')),
                ('specialization', models.CharField(max_length=300, verbose_name='specialization')),
                ('year_of_ending', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_resumes', to='employee_app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('specialization', models.CharField(max_length=300, verbose_name='specialization')),
                ('year_of_ending', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_resumes', to='employee_app.resume')),
            ],
        ),
    ]
