# Generated by Django 4.0.2 on 2022-02-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_favoritevacancies_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritevacancies',
            name='company',
        ),
    ]
