# Generated by Django 4.0.2 on 2022-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_remove_favoritevacancies_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='moderation_status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'under_review'), ('APPROVED', 'approved'), ('NOT_APPROVED', 'not_approved')], default='UNDER_REVIEW', max_length=20, verbose_name='moderation_status'),
        ),
    ]
