# Generated by Django 4.0.2 on 2022-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_resume_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='year_of_ending',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_ending',
            field=models.DateField(blank=True),
        ),
    ]
