# Generated by Django 4.0.2 on 2022-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_alter_courses_year_of_ending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='year_of_ending',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_ending',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
